[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff.workspace = true
blake2.workspace = true
thiserror.workspace = true
sha3.workspace = true

[dev-dependencies]
felt = { path = "../felt" }
hex-literal.workspace = true