[workspace]
members = ["felt", "merkle", "poseidon"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
blake2 = "0.10.6"
hex-literal = "0.4.1"
thiserror = "1.0.63"
sha3 = "0.10.8"