[package]
name = "pedersen"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ark-ff.workspace = true
ark-ec.workspace = true
felt = { path = "../felt"}
num-bigint.workspace = true
anyhow.workspace = true
lazy_static.workspace = true